# Oasis Ecosystem
title = "Oasis Projects"

# Repositories

[[repo]]
url = "https://github.com/therealbryanho/super-chad-adventures/blob/main/README.md"

[[repo]]
url = "https://github.com/IntoTheVerse-Oasis-GameFi"

[[repo]]
url = "https://github.com/w3itch-crafter/w3itch-backend"

[[repo]]
url = "https://github.com/fakeboom/hackathon"

[[repo]]
url = "https://github.com/adi99/Adicia"

[[repo]]
url = "https://github.com/blockystack"

[[repo]]
url = "https://github.com/petacreepers23/PizzaClickerGitcoin"

[[repo]]
url = "https://github.com/ephere-football/virrey"

[[repo]]
url = "https://github.com/AmbrusStudio/account-backend"

[[repo]]
url = "https://github.com/Brianspha/block.difficulty"

[[repo]]
url = "https://github.com/cherideal"

[[repo]]
url = "https://github.com/leon-do/indao-oasis/"

[[repo]]
url = "https://github.com/RoseVerse-MetaFury"

[[repo]]
url = "https://github.com/oxydev/Histopia-Statics"

[[repo]]
url = "https://github.com/MixVerse/"

[[repo]]
url = "https://github.com/mranoncoder"

[[repo]]
url = "https://github.com/metacryptom"

[[repo]]
url = "https://github.com/xdao-app/xdao-contracts/blob/master/contracts/modules/PayrollModule.sol"

[[repo]]
url = "https://github.com/hazelnutcloud/legions-of-oasis"

[[repo]]
url = "https://github.com/LockJar"

[[repo]]
url = "https://github.com/harshu4/NFT-Hunt"

[[repo]]
url = "https://github.com/nospaceleftondevice/PlayAGame"

[[repo]]
url = "https://github.com/cryptoleek-eth/gamebox-oasis-hackathon"

[[repo]]
url = "https://github.com/jrastit/animaldominance"

[[repo]]
url = "https://github.com/BitLoanLab"

[[repo]]
url = "https://github.com/caloriecoin"

[[repo]]
url = "https://github.com/Chaqo/Connext"

[[repo]]
url = "https://github.com/AmaraFinance?tab=repositories"

[[repo]]
url = "https://github.com/albert-vo-crypto/tile-games"

[[repo]]
url = "https://github.com/NASH-METAVERSE"

[[repo]]
url = "https://github.com/mantlefi"

[[repo]]
url = "https://github.com/PolyWars"

[[repo]]
url = "https://github.com/cliffxing/FusionRoblox"

[[repo]]
url = "https://github.com/Aircoin-official/AirCash"

[[repo]]
url = "https://github.com/Nbankloan/NBank-oasis-bloom"

[[repo]]
url = "https://github.com/Uzoprotocol/UZO-DApp-Protocol/tree/Game-Fi-Mechanics-V1"

[[repo]]
url = "https://github.com/Gambleswap"

